"""Remove iban field

Revision ID: 6aff6cd90850
Revises: d32a3c69c1ef
Create Date: 2025-09-21 00:18:23.862598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6aff6cd90850'
down_revision = 'd32a3c69c1ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_column('iban')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('iban', sa.VARCHAR(length=34), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
