"""user_report_fields

Revision ID: 7bb7597c0ebf
Revises: 3b9d72dd1f80
Create Date: 2025-08-14 01:24:02.412048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bb7597c0ebf'
down_revision = '3b9d72dd1f80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint('categories_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_constraint('reports_url_file_key', type_='unique')
        batch_op.drop_column('url_file')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_attempts', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password_attempts')

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url_file', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('reports_url_file_key', ['url_file'])

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('categories_user_id_fkey', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
