"""user_avatar

Revision ID: 824a3201033f
Revises: 5cc4ce6a8703
Create Date: 2026-05-16 16:17:52.131905

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "824a3201033f"
down_revision = "5cc4ce6a8703"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("avatar", sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("avatar")

    # ### end Alembic commands ###
