"""xpub_hash

Revision ID: d168a63bef20
Revises: a67da0ac8185
Create Date: 2026-01-31 19:44:00.607785

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d168a63bef20"
down_revision = "a67da0ac8185"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("wallets", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("xpub_hash", sa.String(length=128), nullable=True)
        )
        batch_op.drop_constraint("wallets_address_key", type_="unique")
        batch_op.create_unique_constraint(None, ["id"])
        batch_op.create_unique_constraint(None, ["xpub_hash"])
        batch_op.drop_column("address")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("wallets", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "address", sa.VARCHAR(length=128), autoincrement=False, nullable=False
            )
        )
        batch_op.drop_constraint(None, type_="unique")
        batch_op.drop_constraint(None, type_="unique")
        batch_op.create_unique_constraint("wallets_address_key", ["address"])
        batch_op.drop_column("xpub_hash")

    # ### end Alembic commands ###
