"""cascade_deletion

Revision ID: d32a3c69c1ef
Revises: aafda40bb1cd
Create Date: 2025-08-27 18:23:44.397806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd32a3c69c1ef'
down_revision = 'aafda40bb1cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operations', schema=None) as batch_op:
        batch_op.drop_constraint('operations_report_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'reports', ['report_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_constraint('reports_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('reports_user_id_fkey', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('operations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('operations_report_id_fkey', 'reports', ['report_id'], ['id'])

    # ### end Alembic commands ###
