"""remove locked

Revision ID: f9e91fdfff01
Revises: 7bb7597c0ebf
Create Date: 2025-08-24 01:06:15.413127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9e91fdfff01'
down_revision = '7bb7597c0ebf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_attempts',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('locked')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('locked', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.alter_column('password_attempts',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
