"""xpub

Revision ID: fcbda73e9deb
Revises: d168a63bef20
Create Date: 2026-01-31 22:28:21.980743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcbda73e9deb'
down_revision = 'd168a63bef20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('xpub', sa.String(length=256), nullable=False))
        batch_op.drop_constraint('wallets_xpub_hash_key', type_='unique')
        batch_op.create_unique_constraint(None, ['xpub'])
        batch_op.drop_column('xpub_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('xpub_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('wallets_xpub_hash_key', ['xpub_hash'])
        batch_op.drop_column('xpub')

    # ### end Alembic commands ###
