services:
  api:
    image: zerox-api:latest
    build: ./
    ports:
      - '5000:5000'
    volumes:
      - .:/api
    env_file:
      - ./.env
    restart: always
  redis:
    image: redis:latest
    init: true
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: always
